# Generated by Django 3.2.12 on 2022-03-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0002_reponseuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponseuser',
            name='reponse',
        ),
        migrations.AddField(
            model_name='reponseuser',
            name='question',
            field=models.ManyToManyField(to='questionnaires.Question'),
        ),
        migrations.AlterField(
            model_name='reponseuser',
            name='votreReponse',
            field=models.BooleanField(default=False),
        ),
    ]
