# Generated by Django 3.2.12 on 2022-03-27 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0003_auto_20220327_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponseuser',
            name='question',
        ),
        migrations.AddField(
            model_name='reponseuser',
            name='reponse',
            field=models.ManyToManyField(to='questionnaires.Reponse'),
        ),
        migrations.AlterField(
            model_name='reponseuser',
            name='votreReponse',
            field=models.BooleanField(),
        ),
    ]
