# Generated by Django 3.2.12 on 2022-03-27 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0004_auto_20220327_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reponseuser',
            old_name='votreReponse',
            new_name='estVrai',
        ),
    ]
