# Generated by Django 3.2.12 on 2022-03-28 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0005_rename_votrereponse_reponseuser_estvrai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reponse',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.question'),
        ),
    ]
