# Generated by Django 3.2.12 on 2022-03-28 17:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionnaires', '0007_alter_question_questionnaire'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='reponseuser',
            name='reponse',
        ),
        migrations.AddField(
            model_name='reponseuser',
            name='reponse',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, to='questionnaires.reponse'),
        ),
        migrations.AlterField(
            model_name='reponseuser',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
