# Generated by Django 3.2.12 on 2022-03-28 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionnaires', '0010_auto_20220328_1950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reponseuser',
            name='reponse',
        ),
        migrations.AddField(
            model_name='reponseuser',
            name='reponse',
            field=models.ManyToManyField(to='questionnaires.Reponse'),
        ),
    ]
